### PR TITLE
generate random relay key when none found

### LINKED ISSUE #333: Generate a random relay key if none found
Right now, if the user does not set a relay key the builder fails. Instead, we should set a random key.

### PR DESCRIPTION
**Pull request by faheelsattar**
## 📝 Summary
Generates a random relay secret key when none is set
Closes #333

## 💡 Motivation and Context
---

## ✅ I have completed the following steps:

* [x] Run `make lint`
* [x] Run `make test`
* [ ] Added tests (if applicable)

### CODE REVIEW

File: crates/rbuilder/src/live_builder/config.rs [hunk 1]
```diff
@@ -267,6 +270,17 @@ impl L1Config {
...
+
+    fn get_relay_secret_key(&self) -> String {
+        if let Some(secret_key) = &self.relay_secret_key {
+            if let Ok(resolved_key) = secret_key.value() {
+                return resolved_key;
+            }
+        }
+        warn!("No relay secret key provided. A random key will be generated.");
+        let secret_key = SecretKey::new(&mut rand::thread_rng());
+        hex::encode(secret_key.secret_bytes())
```
Comment (ferranbt) [inline crates/rbuilder/src/live_builder/config.rs]: Do not convert to string to convert back to BLSBlockSigner

File: crates/rbuilder/src/live_builder/config.rs [hunk 2]
```diff
@@ -267,6 +270,17 @@ impl L1Config {
         ));
         Ok((sink_factory, relays))
     }
+
+    fn get_relay_secret_key(&self) -> String {
```
Comment (ferranbt) [inline crates/rbuilder/src/live_builder/config.rs]: Please inline this in `submission_config`.

File: crates/rbuilder/src/live_builder/config.rs [hunk 3]
```diff
@@ -267,6 +270,17 @@ impl L1Config {
...
+        if let Some(secret_key) = &self.relay_secret_key {
+            if let Ok(resolved_key) = secret_key.value() {
```
Comment (ferranbt) [inline crates/rbuilder/src/live_builder/config.rs]: Handle the error case with ?

**Review by ferranbt — COMMENTED** [review]
Thank you for the PR. I left a few notes.

File: crates/rbuilder/src/live_builder/config.rs (hunk 1 above)
Comment (faheelsattar) [reply crates/rbuilder/src/live_builder/config.rs]: passing `SecretKey` directly now

**Review by ferranbt — APPROVED** [review]
