### PR TITLE
Fail if no relays are configured

### LINKED ISSUE #304: If `dry_run` is not enabled and there are no relays set, the builder should fail
If the builder is not in `dry_run` mode and the relays list is empty, the builder starts and it does nothing. It needs the relay to generate the mev slot data in `MevSlotDataGenerator`.

Currently, we rely on watchdog to stop the process eventually if there are no slots found, but we are trying to remove this behaviour.

### LINKED ISSUE #319: The L1 rbuilder should not run if no relays are enabled and not in dry run mode
If not in `dry_run` mode and there are no relays configured, the builder should fail.

### PR DESCRIPTION
**Pull request by ferranbt**
## 📝 Summary

Closes #304 

## 💡 Motivation and Context

---

## ✅ I have completed the following steps:

* [ ] Run `make lint`
* [ ] Run `make test`
* [ ] Added tests (if applicable)

### CODE REVIEW

**Comment by ZanCorDX** [comment]
Why do you check for ```!self.dry_run && relays.is_empty()```?
Wouldn't it also fail in dryrun mode with no relays since it can't get the slot info on tha main loop?

**Comment by ferranbt** [comment]
True, I have to do only `relays.is_empty()` only.

File: crates/rbuilder/src/live_builder/config.rs [hunk 1]
```diff
@@ -278,6 +278,10 @@ impl L1Config {
         );
 
         let relays = self.create_relays()?;
+        if relays.is_empty() {
+            eyre::bail!("No relays provided");
+        }
```
Comment (liamaharon) [inline crates/rbuilder/src/live_builder/config.rs:283]: `op-rbuilder` doesn't require relays. With all the assumptions the `new_builder` method makes about L1 specific config, maybe it should be renamed `new_l1_builder`?

**Review by liamaharon — APPROVED** [review]

File: crates/rbuilder/src/live_builder/config.rs (hunk 1 above)
Comment (ferranbt) [reply crates/rbuilder/src/live_builder/config.rs:283]: Agree, my goal is to end up with a chain-agnostic core block building and then make LiveBuilder the specific instance that "wires" that block builder for the Ethereum L1 chain.

**Review by ZanCorDX — APPROVED** [review]
